[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production]
  environment = { CONTEXT = "production" }

[context.deploy-preview]
  environment = { CONTEXT = "deploy-preview" }

[context.branch-deploy]
  environment = { CONTEXT = "branch-deploy" }